--- # webserver setup
- hosts: webserver
  remote_user: test5000
  become: yes
  tasks:
    - name: installing httpd package
      yum: name=httpd state=installed
      when: ansible_os_family == "RedHat" and ansible_hostname == "server2"
    - name: installing apache package
      yum: name=apache2 state=installed
      when: ansible_os_family == "Debian"
    - name: copy index.html
      copy: src=index.html dest=/var/www/html/index.html
    - name: start httpd service
      service: name=httpd state=started
      register: result
    - debug: var=result
